spring:
  datasource:
    main:
      jdbc-url: jdbc:mysql://39.105.47.81:3306/nucleic
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
    # 平台用户库
    sxuh:
      jdbc-url: jdbc:oracle:thin:@192.168.1.243:1521:HARSDEV
      driver-class-name: oracle.jdbc.OracleDriver
      username: ferry
      password: ferry
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    generate-ddl: true


